0 = log
1 = sender - filelist
2 = generateur - demande de fichier 
3 = generateur - fin du generateur
4 = sneder - envoie de fichier debut
5 = sender - envoie de fichier en cours 
6 = sender - envoie de fichier fin 
7 = generateur - nouveau dossier 
8 = sender - nouveau dossier
9 = sender - fin de l'étape : envoie de fichier / dossier
10 = generateur,sender - demande de suprimer un fichier
11 = generateur, sender - demande d'update de fichier
12 = receiver - envoie (taille du hash, hash)
13 = sender - bon hash
14 = sender - mauvais hash
15 = receiver, sender - fin de fichier (update)
16 = mode deamon - push
17 = mode deamon - pull
18 = deamon - list-only mode pull